feat: expose profile url in auth response
blockstack/connect pull request #131
Opened 2021-05-26 13:19 UTC by fbwoolf

## Description

This PR exposes the `profile_url` and other properties in the auth response.

For details refer to issue #127

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No.

## Are documentation updates required?
TBD.

## Testing information
TBD.

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `yarn lerna run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @hstove or @kyranjamie or @aulneau for review

2021-05-26 13:22 UTC, aulneau requested changes
Awesome! thanks for doing this. Just a few comments

2021-05-26 13:22 UTC, aulneau commented on packages/connect/src/auth.ts
> +    .then(async data => {
Since we are in here making updates, wanna convert the authenticate method to an async method and get rid of the ignored provider promise?

2021-05-26 13:22 UTC, aulneau commented on packages/connect/src/auth.ts
> +      await userSession.handlePendingSignIn(data.authResponseToken);
Can you test this doesn't fail when a user cancels auth?

2021-05-26 13:22 UTC, aulneau commented on packages/connect/src/types/auth.ts
> +  finished?: (payload: FinishedAuthData) => void;
Let's make this a breaking change and remove these, users who are up-to-date can easily switch to `onFinish`

2021-05-26 13:32 UTC, aulneau requested changes

2021-05-26 13:32 UTC, aulneau commented on packages/connect/src/types/auth.ts
> +export interface FinishedAuthData extends FinishedAuthPayload {
Thinking more about this, I think the best thing to do would not include any work in the extension to make this possible, and persist the same "authResponse" type as string, and include a new key of `authResponsePayload`, so like this:
```ts
export interface FinishedAuthData {
  authResponse: string;
  authResponsePayload: AuthResponsePayload;
  userSession: UserSession;
}
```

2021-05-26 14:31 UTC, fbwoolf commented on packages/connect/src/auth.ts
> +      const token = decodeToken(authResponse); // authResponse is returned from a successful authentication
Will remove this comment.

2021-05-27 12:59 UTC, aulneau requested changes
Great! much better, just one change request

2021-05-27 12:59 UTC, aulneau commented on packages/connect/src/auth.ts
> +  await provider
when switching away from `.then` etc to an async await pattern, this would be updated as such:
before:
```ts
  void provider
    .authenticationRequest(authRequest)
    .then(async authResponse => {
        await userSession.handlePendingSignIn(authResponse);
        const token = decodeToken(authResponse);
        const payload = token?.payload;
        const authResponsePayload = (payload as unknown) as AuthResponsePayload;
        onFinish?.({
            authResponse,
            authResponsePayload,
            userSession,
        });
    })
    .catch(error => {
        console.error('[Connect] Error during auth request', error);
        onCancel?.();
    });
  ```
```ts
    try {
        const authResponse = await provider.authenticationRequest(authRequest)
        await userSession.handlePendingSignIn(authResponse);
        const token = decodeToken(authResponse);
        const payload = token?.payload;
        const authResponsePayload = (payload as unknown) as AuthResponsePayload;
        onFinish?.({
            authResponse,
            authResponsePayload,
            userSession,
        });
    } catch (error) {
        console.error('[Connect] Error during auth request', error);
        onCancel?.();
    }
```

2021-05-27 13:02 UTC, aulneau commented
We should probably remove and `finish` instances, too https://github.com/blockstack/connect/blob/main/packages/connect-react/src/react/hooks/use-connect.ts#L71

@fbwoolf could you remove `finish` from the transaction request methods too?

2021-05-27 13:12 UTC, fbwoolf commented on packages/connect/src/auth.ts
> +  await provider
Right, my bad, thanks!

2021-05-27 13:13 UTC, fbwoolf commented
> We should probably remove and `finish` instances, too https://github.com/blockstack/connect/blob/main/packages/connect-react/src/react/hooks/use-connect.ts#L71
> 
> @fbwoolf could you remove `finish` from the transaction request methods too?

Yep, for sure, was thinking I should too. 👍

2021-05-27 21:28 UTC, fbwoolf commented on packages/connect/src/transactions/index.ts
>    void provider
Should I switch this to an async/await too?

2021-05-27 21:29 UTC, aulneau commented on packages/connect/src/transactions/index.ts
>    void provider
Yes, please

2021-05-28 18:13 UTC, fbwoolf commented
I realized this breaks the web wallet test-app bc the app auth uses `finished` and needs to be changed to `onFinish`.

2021-06-08 19:45 UTC, aulneau approved these changes

2021-06-09 17:41 UTC, merged