fix: moved tsdx from dependencies to devDependencies
blockstack/connect pull request #132
Opened 2021-05-26 20:38 UTC by pgray-hiro

## Description

This PR moves the `tsdx` package from `dependencies` to `devDependencies`.  This should resolve an error with the Todos App dev tutorial where a downstream dependency was failing a yarn preflight check.

For more details, see https://github.com/blockstack/docs/issues/1170.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `yarn lerna run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @hstove or @kyranjamie or @aulneau for review

2021-05-26 20:41 UTC, aulneau requested changes

2021-05-26 20:41 UTC, aulneau commented on package.json
> +    "postinstall-postinstall": "^2.1.0"
while we're at it, the dependencies should only be:
```    "bn.js": "^5.2.0",    "buffer": "^6.0.3",    "is-regex": "^1.1.2",    "jsx-ast-utils": "^3.2.0",```

2021-05-26 20:42 UTC, aulneau commented on package.json
> +    "postinstall-postinstall": "^2.1.0"
everything else _should_ be a dev dependency if i'm not mistaken

2021-05-26 21:00 UTC, fbwoolf reviewed
`tsdx` is also in the dependencies in the connect package itself.

2021-05-27 12:23 UTC, pgray-hiro commented
@aulneau Do I need to make a changeset here? The bot is nagging me. I'll update the dependencies.

2021-05-27 12:31 UTC, pgray-hiro commented
Hopefully I did that right, my terminal output said I only did a minor bump to `@stacks-connect` but the bot is saying there's a major bump to `@stacks/connect-react` - not sure why.

2021-05-27 12:33 UTC, aulneau commented on .changeset/ninety-teachers-hunt.md
> +updated dependencies
Let's try to keep this a bit more verbose if possible, https://github.com/blockstack/connect/blob/main/packages/connect/CHANGELOG.md we want to make sure reading the changelog is fun and enjoyable!

maybe something like this:

> This update moves `tsdx` and other dependencies to the correct category of `devDependencies`, fixing a downstream issue in the todos example app.

2021-05-27 12:34 UTC, aulneau commented on .changeset/ninety-teachers-hunt.md
> +updated dependencies
You can edit this markdown file after the initial `yarn changeset` command to be whatever you like.

2021-05-27 12:40 UTC, pgray-hiro commented
Sounds good, updated.

2021-05-27 12:54 UTC, merged