refactor: onboarding after install
blockstack/connect pull request #148
Opened 2021-06-15 13:35 UTC by fbwoolf

## Description

This PR changes the onboarding flow so that now after install the user is directed back to their app tab and it reloads the page so the extension can be detected as installed. This will be paired with changes to the stacks-web-wallet.

For details refer to issue #44 

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No.

## Are documentation updates required?
No.

## Testing information
Testing will be handled by devs.

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `yarn lerna run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @hstove or @kyranjamie or @aulneau for review

2021-06-15 13:38 UTC, kyranjamie commented on packages/connect-ui/src/components.d.ts
> +        "appUrl": string;
This is autogenerated? 🤔

2021-06-15 13:52 UTC, fbwoolf commented on packages/connect-ui/src/components.d.ts
> +        "appUrl": string;
What do you mean by this? I am still learning types. These changes were autogenerated when I added the new prop to the stencil component.

2021-06-15 20:16 UTC, fbwoolf commented
After looking at this closer, there is a `redirectTo` property on the `AuthOptions`, but we would be relying on the app dev to include it bc it is optional or we can force it like I am doing here.

2021-06-16 07:55 UTC, kyranjamie commented on packages/connect-ui/src/components.d.ts
> +        "appUrl": string;
Alright, yeah was curious to know (mostly as they don't follow our formatting pattern), not a concern when autogenerated.

2021-06-16 07:55 UTC, kyranjamie approved these changes

2021-06-21 16:21 UTC, aulneau requested changes

2021-06-21 16:21 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
I wonder if we should use the `redirectUrl` in place of `appUrl`

2021-06-21 16:21 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
@kyranjamie does this need sanitation you think?

2021-06-21 16:21 UTC, aulneau commented on packages/connect/src/utils.ts
>    return window.StacksProvider || window.BlockstackProvider;
We are no longer injecting `BlockstackProvider`
```suggestion
  return window.StacksProvider;
```

2021-06-21 16:49 UTC, kyranjamie commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
Good spot. Yes, we should validate that this is a URL. What happens if the user enters: `javascript:window.alert("lol")` ?

2021-06-21 17:22 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
Do you mean the `redirectTo` url set in the `authOptions` by the app? I wasn't sure if we could rely on that since it is optional? From comments in the wallet PR, maybe we should keep track of the specific tabId instead in case there are several tabs of the app open?

2021-06-21 17:23 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
yeah, I think keeping track of the tabId makes the most sense, but if possible we should try to implement any redirect behavior in a different PR.

2021-06-21 17:24 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
if we can scope this change to basically be "the app will update when the extension has been installed" or basically everything other than redirection, i think that would make our lives easier. things get tricky when trying to redirect, and it's a bigger project which i think requires some UX considerations

2021-06-21 17:28 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
I'm not sure then that any of this work satisfies closing the 2 linked issues? Should I just make a third issue with that scope and leave those 2 open for the new design work?

2021-06-21 19:16 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
With this scope of just reloading, I should prob keep using the url (not a specific tabId) and reload any tabs open with the app url?

2021-06-21 19:18 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
based on this issue: https://github.com/blockstack/connect/issues/144 we should not do any reloading, but instead give them two options: "Head back to App" or "close tab"

2021-06-21 19:24 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
What is the best way to do this?

2021-06-21 19:27 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
I don't totally understand this, the user isn't entering anything here ...it is taken from `window.location.href` from where they launched the install modal.

2021-06-21 19:28 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
https://github.com/blockstack/stacks-wallet-web/blob/main/src/common/utils.ts#L51

2021-06-21 19:30 UTC, aulneau commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
anytime we are taking a URL from some arbitrary location we should sanitize it, anything can be hijacked

2021-06-21 20:02 UTC, fbwoolf commented on packages/connect-ui/src/components/modal/modal.tsx
> +  @Prop() appUrl: string;
This one is where I started and it mentions not wanting the user to have to manually refresh ...the first step was getting rid of that modal: https://github.com/blockstack/connect/issues/98 which prompted them to refresh after install. I thought the goal was to it for them.

2021-06-22 09:19 UTC, kyranjamie commented on packages/connect-ui/src/components/modal/modal.tsx
> +    urlParams.set('app', this.appUrl);
Yeah indeed, the href could be set maliciously. We have a 1:1 later Fara, I'll run you through how one of the h1 exploit reports figured out an XSS ☠️

2021-06-24 01:20 UTC, closed without merging